# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install --upgrade pip
    post_install:
      - pip install -e .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

submodules:
  include: all
  recursive: true